_storage {
  type = postgres
  config {
    dataSourceClass = "org.postgresql.ds.PGSimpleDataSource"
    properties = {
      serverName = postgres
      portNumber = 5432
      user =  canton-admin
      password = canton-admin
      # tcpKeepAlive = true
    }
  }
  parameters {
    # max-connections = 32
    migrate-and-start = false
  }
}

canton {
    mediators {
        mediator1 {
            admin-api {
                port = 6869
            }
            storage = ${_storage}
            storage.config.properties.databaseName = mediator
        }
    },
    participants {
        sandbox {
            monitoring.grpc-health-server {
              address = 0.0.0.0
              port = 5061
            }
            admin-api {
                port = 6866
            },
            http-ledger-api {
                port = 6864
            },
            ledger-api {
                port = 6865
                address = 0.0.0.0
                tls = null
                user-management-service {
                    enabled = true
                }
            },
            # storage {
            #     type = "memory"
            # }
            storage = ${_storage}
            storage.config.properties.databaseName = participant
        }
    },
    sequencers {
        sequencer1 {
            admin-api {
                port = 6868
            },
            public-api {
                port = 6867
            },
            sequencer {
                config {
                    # storage {
                    #     type = "memory"
                    # }
                    storage = ${_storage}
                    storage.config.properties.databaseName = sequencer
                },
                type = "reference"
            },
            # storage {
            #     type = "memory"
            # }
            storage = ${_storage}
            storage.config.properties.databaseName = driver
        }
    }
}
